### ISSUE TITLE
Potentially add an icon to Safari Reader

### ISSUE THREAD

**Issue by rufo** [rufo/instafari#2]
So [@matiassingers](http://twitter.com/matiassingers) on Twitter had the following idea:

> @rufo I just looked at the code for Instafari and that look really simple and easy. I then looked at Apple's Reader code- simple HTML CSS JS [src](http://twitter.com/matiassingers/status/15779449256)
> 
> @rufo so is there anyway to implement at Instapaper button down there next to print and the other ones - so it would go to Instapaper. [src](http://twitter.com/matiassingers/status/15779449256)

I haven't looked into the feasibility of this yet (though I'm very intrigued by the fact Reader is all CSS/JS magic), but the main thing that crosses my mind is Instapaper's API only accepts a URL/title, and no body text - so Instapaper wouldn't be able to take advantage of the various techniques Safari Reader uses to massage the text and pages into one article. This seems like it might be unexpected behavior.

There are also questions of how multi-page articles should be handled. It looks like Reader only loads the subsequent pages when you scroll down to the bottom of the current page - without having looked at Reader's code, I'm not sure if we'd be able to pass each page's URL into Instapaper.

Still, this might be interesting to play around with; it could always be an "experimental" preference.

**Comment by jeroenleenarts** [comment]
This should be possible with the code insertion abilities of the Safari Extensions API. From what I can tell from the docs it's a matter of adding a script injection.

Details are available here:
http://developer.apple.com/safari/library/documentation/Tools/Conceptual/SafariExtensionGuide/InjectingScripts/InjectingScripts.html#//apple_ref/doc/uid/TP40009977-CH6-SW1

After inserting the script it's a matter of doing some DOM modification. (Docs contain a small example.) Couldn't find anything about reusing the global html/script yet though. Since the page and extension namespaces seem to be seperated by a messaging pipeline I think the easiest sollution would be to replicate the same behavior with some inserted scripts right inside the injected script.

**Comment by rufo** [comment]
I poked at this a bit, but couldn't figure out a way to inject code into the Reader.html page.

According to the [Whitelists and Blacklists](http://developer.apple.com/safari/library/documentation/Tools/Conceptual/SafariExtensionGuide/ExtensionPermissions/ExtensionPermissions.html#//apple_ref/doc/uid/TP40009977-CH8-DontLinkElementID_7) section in the development guide, you can only inject code into http and https URLs; I tried a few different ways to get Safari to inject code into the special Reader.html URL (safari-resource:/Reader.html), but no dice so far, and it doesn't appear that Safari is adding code to the parent page.

Unless we can figure out a way around this or Apple adds official support (I'll file a bug), I believe this isn't feasible for now.

**Comment by rufo** [comment]
Filed http://openradar.appspot.com/8076092 with Apple - closing for now.
